# Generated by Django 4.1.7 on 2023-04-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_category_name_alter_post_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='dateadded',
            field=models.DateTimeField(default='2023-04-10'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(max_length=200),
        ),
    ]
