# Generated by Django 4.1.7 on 2023-09-10 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment_dateadded_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='photo',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='featuredImage',
            field=models.TextField(default=''),
        ),
    ]
