# Generated by Django 4.1.7 on 2023-09-13 18:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_author_photo_alter_post_featuredimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
